# / ===================================================== \
# |  This is the main configuration file of OreAnnouncer  |
# \ ===================================================== /
#
# For any problem be sure to:
# - Read the entire documentation on: https://alessiodp.com/docs/oreannouncer/
# - Join our Discord for further help: https://discord.alessiodp.com/
#

# / =============================== \
# |      OREANNOUNCER SETTINGS      |
# \ =============================== /
oreannouncer:
  # [Check for plugins updates]
  # OreAnnouncer will check for updates when the server finishes to load.
  updates:
    check: true
    warn: true

  # [Enable logging system]
  # => debug:      Print debug messages
  # => save-file:  Save any log into a text file
  logging:
    debug: false
    save-file:
      enable: false
      format: "%date% [%time%] %message%\n"
      file: log.txt


# / =============================== \
# |        STORAGE  SETTINGS        |
# \ =============================== /
storage:
  # [Database type]
  # What type of storage the plugin should use? Database storage types:
  # => mysql      | [Remote] Save the data into a MySQL database
  # => sqlite     | [File]   Save the data into a SQLite database (default)
  # => h2         | [File]   Save the data into a H2 database
  database-storage-type: sqlite

  storage-settings:
    # [General SQL settings]
    # General settings for sql databases, recommended to use default values
    general-sql-settings:
      prefix: 'oreannouncer_'
      # Available: UTF-8, UTF-16le & UTF-16be
      charset: 'UTF-8'

    # [SQLite settings]
    sqlite:
      database-file: database.db

    # [H2 settings]
    h2:
      database-file: database

    # [MySQL settings]
    mysql:
      address: localhost
      port: '3306'
      database: database
      username: username
      password: password
      # Size of the connection pool
      pool-size: 10
      # Lifetime of each connection, in milliseconds (Default: 30 minutes = 1800000ms)
      connection-lifetime: 1800000
      # Property used to alert when the connection is not using a valid SSL certificate
      use-ssl: false


# / =============================== \
# |         ALERTS SETTINGS         |
# \ =============================== /
alerts:
  # [Enable alerts system]
  # Whenever a player dig a block users/admins/console will receive a message
  enable: true
  console: true


# / =============================== \
# |         BLOCKS SETTINGS         |
# \ =============================== /
blocks:
  # Allowed blocks to handle
  # You can use '*' to handle every block that is received from servers
  list-allowed:
    - '*'


# / =============================== \
# |         STATS  SETTINGS         |
# \ =============================== /
stats:
  # [Statistics system]
  # Start to store any data about destroyed blocks, enables:
  # => /oa stats:  Show destroyed blocks stats about a player
  # => /oa top:    Show top players
  # You can enable/disable every block manually with 'count-on-destroy' option
  #
  # [Advanced count]
  # Store any data about found blocks, this will enable a time tracking logging
  # of blocks for an improved anti x-ray system.
  # You have to configure blocks options to use this.
  enable: true
  # Order by:
  # => priority = Block priority number
  # => value    = Value
  order-by: priority
  # Insert any block that you want to blacklist from general listing
  blacklist-blocks:
    log: []
    stats: []
    top:
      - 'STONE'
  advanced-count:
    enable: true
    # Time format:
    # => y          years
    # => M          months
    # => d          days
    # => H          hours
    # => m          minutes
    # => s          seconds
    # => S          milliseconds
    # => 'text'     arbitrary text content
    default-time-format: "m' minutes'"

    log-command:
      enable: true
      # Simple date format
      format-date: "yyyy-MM-dd 'at' HH:mm"
      # See time format above
      # => large     = More than 1 day
      # => medium    = More than 1 hour
      # => small     = More than 1 minute
      # => smallest  = More than 0
      format-date-elapsed-large: "d'd' H'h'"
      format-date-elapsed-medium: "H'h' m'm'"
      format-date-elapsed-small: "m'm' s's'"
      format-date-elapsed-smallest: "s's'"
      number-of-blocks: 8
  top:
    enable: true
    # Order by: destroy/found
    order-by: destroy
    # Allow order change with the command
    change-order: false
    number-of-players: 5


# / =============================== \
# |        COMMANDS SETTINGS        |
# \ =============================== /
commands:
  # Enable tab support (/oab <tab> to see every allowed command)
  tab-support: true
  oa-description: OreAnnouncer help page
  main-commands:
    help: help
    oa: oab
    alerts: alerts
    log: log
    reload: reload
    stats: stats
    top: top
    version: version
  sub-commands:
    block: 'block'
    player: 'player'
    word-on: 'on'
    word-off: 'off'
  order:
    - help
    - alerts
    - log
    - stats
    - top
    - reload
    - version


dont-edit-this:
  version: 4