# / ===================================================== \
# |  This is the main configuration file of OreAnnouncer  |
# \ ===================================================== /
#
# For any problem be sure to:
# - Read the entire documentation on: https://alessiodp.com/docs/oreannouncer/
# - Join our Discord for further help: https://discord.alessiodp.com/
#

# / =============================== \
# |      OREANNOUNCER SETTINGS      |
# \ =============================== /
oreannouncer:
  # [Check for plugins updates]
  # OreAnnouncer will check for updates when the server finishes to load.
  updates:
    check: true
    warn: true

  # [Enable logging system]
  # => debug:      Print debug messages
  # => save-file:  Save any log into a text file
  logging:
    debug: false
    save-file:
      enable: false
      format: "%date% [%time%] %message%\n"
      file: log.txt


# / =============================== \
# |        STORAGE  SETTINGS        |
# \ =============================== /
storage:
  # [Database type]
  # What type of storage the plugin should use? Database storage types:
  # => mysql      | [Remote] Save the data into a MySQL database
  # => sqlite     | [File]   Save the data into a SQLite database (default)
  database-storage-type: sqlite

  storage-settings:
    # [General SQL settings]
    # General settings for sql databases, recommended to use default values
    general-sql-settings:
      varchar-size: 255
      upgrade:
        save-old-table: true
        old-table-suffix: _backup
      tables:
        players: oreannouncer_players
        blocks: oreannouncer_blocks
        blocks-found: oreannouncer_blocks_found
        versions: oreannouncer_versions

    # [SQLite settings]
    sqlite:
      database-file: database.db

    # [MySQL settings]
    mysql:
      address: localhost
      port: '3306'
      database: database
      username: username
      password: password
      # Size of the connection pool
      pool-size: 10
      # Lifetime of each connection, in milliseconds (Default: 30 minutes = 1800000ms)
      connection-lifetime: 1800000
      # Property used to alert when the connection is not using a valid SSL certificate
      use-ssl: false
      # Charset used by tables
      charset: utf8


# / =============================== \
# |         ALERTS SETTINGS         |
# \ =============================== /
alerts:
  # [Enable alerts system]
  # Whenever a player dig a block users/admins/console will receive a message
  enable: true
  console: true



# / =============================== \
# |         BLOCKS SETTINGS         |
# \ =============================== /
blocks:
  # Allowed blocks to handle
  # You can use '*' to handle every block that is received from servers
  list-allowed:
    - '*'


# / =============================== \
# |         STATS  SETTINGS         |
# \ =============================== /
stats:
  # [Statistics system]
  # Start to store any data about destroyed blocks, enables:
  # => /oa stats:  Show destroyed blocks stats about a player
  # => /oa top:    Show top players
  # You can enable/disable every block manually with 'count-on-destroy' option
  #
  # [Advanced count]
  # Store any data about found blocks, this will enable a time tracking logging
  # of blocks for an improved anti x-ray system.
  # You have to configure blocks options to use this.
  enable: true
  advanced-count:
    enable: true
    # Time format:
    # => y          years
    # => M          moths
    # => d          days
    # => H          hours
    # => m          minutes
    # => s          seconds
    # => S          milliseconds
    # => 'text'     arbitrary text content
    default-time-format: "m' minutes'"
  top:
    enable: true
    # Order by: destroy/found
    order-by: destroy
    number-of-players: 5
    page-size: 5


# / =============================== \
# |        COMMANDS SETTINGS        |
# \ =============================== /
commands:
  # Enable tab support (/oa <tab> to see every allowed command)
  tab-support: true
  oa-description: OreAnnouncer help page
  main-commands:
    help: help
    oa: oa
    alerts: alerts
    reload: reload
    stats: stats
    top: top
    version: version
  sub-commands:
    word-on: 'on'
    word-off: 'off'


dont-edit-this:
  version: 2