name: ${pluginName}
description: ${pluginDescription}
author: ${pluginAuthor}
website: ${pluginWebsite}
version: ${pluginVersion}
main: com.alessiodp.oreannouncer.bukkit.bootstrap.BukkitOreAnnouncerBootstrap
api-version: 1.13
softdepend: [LastLoginAPI, PlaceholderAPI]
permissions:
  oreannouncer.user.alerts.see:
    description: See user alerts
  oreannouncer.user.alerts.toggle:
    description: Allow access to /oa alerts
  oreannouncer.user.help:
    description: Allow access to /oa help
  oreannouncer.user.stats:
    description: Allow access to /oa stats
  oreannouncer.user.top:
    description: Allow access to /oa top
  oreannouncer.admin.alerts.see:
    description: See admin alerts
  oreannouncer.admin.reload:
    description: Allow access to /oa reload
  oreannouncer.admin.stats.other:
    description: Allow access to /oa stats on other players
  oreannouncer.admin.updates:
    description: Send a message if there is an update
  oreannouncer.admin.version:
    description: Allow access to /oa version

  oreannouncer.user.*:
    default: op
    description: All user permissions
    children:
      oreannouncer.user.alerts.see: true
      oreannouncer.user.alerts.toggle: true
      oreannouncer.user.stats: true
      oreannouncer.user.top: true
      oreannouncer.user.help: true
  oreannouncer.admin.*:
    default: op
    description: All admin permissions
    children:
      oreannouncer.user.*: true
      oreannouncer.admin.alerts.see: true
      oreannouncer.admin.migrate: true
      oreannouncer.admin.reload: true
      oreannouncer.admin.stats.other: true
      oreannouncer.admin.updates: true
      oreannouncer.admin.version: true