name: ${pluginName}
description: ${pluginDescription}
author: ${pluginAuthor}
website: ${pluginWebsite}
version: ${pluginVersion}
main: com.alessiodp.oreannouncer.bukkit.bootstrap.BukkitOreAnnouncerBootstrap
api-version: 1.13
softdepend: [LastLoginAPI, PlaceholderAPI]
permissions:
  oreannouncer.user.alerts.see:
    description: See user alerts
  oreannouncer.user.alerts.toggle:
    description: Allow access to /oa alerts
  oreannouncer.user.help:
    description: Allow access to /oa help
  oreannouncer.user.stats:
    description: Allow access to /oa stats
  oreannouncer.user.stats.destroy:
    description: Allow access to only /oa stats with destroy type
    default: false
  oreannouncer.user.stats.found:
    description: Allow access to only /oa stats with found type
    default: false
  oreannouncer.user.top:
    description: Allow access to /oa top
  oreannouncer.user.top.destroy:
    description: Allow access to only /oa top with destroy order
    default: false
  oreannouncer.user.top.found:
    description: Allow access to only /oa top with found order
    default: false
  oreannouncer.admin.alerts.see:
    description: See admin alerts
  oreannouncer.admin.bypass.alerts:
    description: Bypass alerts on block destroy
  oreannouncer.admin.bypass.destroy:
    description: Bypass destroy count on block destroy
  oreannouncer.admin.bypass.found:
    description: Bypass found count on block destroy
  oreannouncer.admin.debug:
    description: Allow access to /oa debug
  oreannouncer.admin.log:
    description: Allow access to /oa log
  oreannouncer.admin.reload:
    description: Allow access to /oa reload
  oreannouncer.admin.stats.other:
    description: Allow access to /oa stats on other players
  oreannouncer.admin.version:
    description: Allow access to /oa version
  oreannouncer.admin.warnings:
    description: Send an alert if there is an error

  oreannouncer.user.*:
    default: op
    description: All user permissions
    children:
      oreannouncer.user.alerts.see: true
      oreannouncer.user.alerts.toggle: true
      oreannouncer.user.help: true
      oreannouncer.user.stats: true
      oreannouncer.user.top: true
  oreannouncer.admin.*:
    default: op
    description: All admin permissions
    children:
      oreannouncer.user.*: true
      oreannouncer.admin.alerts.see: true
      oreannouncer.admin.bypass.alerts: true
      oreannouncer.admin.bypass.destroy: true
      oreannouncer.admin.bypass.found: true
      oreannouncer.admin.debug: true
      oreannouncer.admin.log: true
      oreannouncer.admin.reload: true
      oreannouncer.admin.stats.other: true
      oreannouncer.admin.version: true
      oreannouncer.admin.warnings: true